import React, { useState, useEffect } from 'react';
import { useAuth } from '../../contexts/AuthContext';
import { getHallStats, getPayments, getComplaints, updateComplaintStatus, addPayment, getHalls } from '../../services/storageService';
import { ComplaintStatus, UserRole, Payment, Complaint, Hall } from '../../types';
import { Wallet, FileText, CheckCircle, Clock, Loader2 } from 'lucide-react';

const HallDashboard = () => {
  const { user } = useAuth();
  const [activeTab, setActiveTab] = useState<'overview' | 'payments' | 'complaints'>('overview');
  const [loading, setLoading] = useState(true);
  
  const [hallStats, setHallStats] = useState<any>(null);
  const [payments, setPayments] = useState<Payment[]>([]);
  const [complaints, setComplaints] = useState<Complaint[]>([]);
  const [hallName, setHallName] = useState('Hall');

  // Form State for Payment
  const [payAmount, setPayAmount] = useState(20);
  const [payStudentId, setPayStudentId] = useState('');
  const [payReceipt, setPayReceipt] = useState('');
  const [payMsg, setPayMsg] = useState('');

  const refreshData = async () => {
    if (!user || !user.hallId) return;
    
    setLoading(true);
    try {
        const [stats, p, c, halls] = await Promise.all([
            getHallStats(user.hallId),
            getPayments(),
            getComplaints(),
            getHalls()
        ]);
        
        setHallStats(stats);
        setPayments(p.filter(x => x.hallId === user.hallId));
        setComplaints(c.filter(x => x.hallId === user.hallId));
        const currentHall = halls.find(h => h.id === user.hallId);
        if (currentHall) setHallName(currentHall.name);
        
    } catch(err) {
        console.error(err);
    } finally {
        setLoading(false);
    }
  };

  useEffect(() => {
    refreshData();
  }, [user]);

  const handlePayment = async (e: React.FormEvent) => {
    e.preventDefault();
    if(!user || !user.hallId) return;

    const newPayment: Payment = {
        id: '', // Will be generated by DB
        hallId: user.hallId,
        amount: payAmount,
        receiptNumber: payReceipt,
        semester: '2023/2024 - Sem 1',
        studentId: payStudentId,
        studentName: payStudentId, // Mock name
        datePaid: new Date().toISOString(),
        recordedBy: user.id
    };
    await addPayment(newPayment);
    setPayMsg('Payment Recorded Successfully!');
    setPayStudentId('');
    setPayReceipt('');
    
    // Refresh list
    await refreshData();
    setTimeout(() => setPayMsg(''), 3000);
  };

  const handleStatusChange = async (id: string, status: ComplaintStatus) => {
    await updateComplaintStatus(id, status);
    await refreshData();
  };
  
  if (!user || !user.hallId) return <div>Hall Access Error</div>;
  if (loading && !hallStats) return <div className="flex h-64 items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-green-600"/></div>;

  return (
    <div className="space-y-6">
       <div className="flex justify-between items-center">
        <h1 className="text-2xl font-bold text-gray-800">{hallName} Dashboard</h1>
        <div className="px-3 py-1 bg-green-100 text-green-800 rounded-full text-sm font-medium">
          {user.role === UserRole.HALL_MASTER ? 'Hall Master' : 'Hall Executive'} Mode
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
           <p className="text-xs text-gray-500 uppercase">Total Collected</p>
           <h3 className="text-2xl font-bold text-gray-800">GH₵ {hallStats?.totalCollected || 0}</h3>
        </div>
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
           <p className="text-xs text-gray-500 uppercase">Pending Complaints</p>
           <h3 className="text-2xl font-bold text-gray-800">{hallStats?.pendingComplaints || 0}</h3>
        </div>
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
           <p className="text-xs text-gray-500 uppercase">Paid Percentage</p>
           <h3 className="text-2xl font-bold text-gray-800">{hallStats?.paidPercentage?.toFixed(1) || 0}%</h3>
        </div>
      </div>

      <div className="flex gap-4 border-b border-gray-200 mt-8">
        <button onClick={() => setActiveTab('overview')} className={`pb-2 px-4 text-sm font-medium ${activeTab === 'overview' ? 'border-b-2 border-green-600 text-green-700' : 'text-gray-500'}`}>Overview</button>
        <button onClick={() => setActiveTab('payments')} className={`pb-2 px-4 text-sm font-medium ${activeTab === 'payments' ? 'border-b-2 border-green-600 text-green-700' : 'text-gray-500'}`}>Record Payment</button>
        <button onClick={() => setActiveTab('complaints')} className={`pb-2 px-4 text-sm font-medium ${activeTab === 'complaints' ? 'border-b-2 border-green-600 text-green-700' : 'text-gray-500'}`}>Complaints</button>
      </div>

      {activeTab === 'overview' && (
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
            <h3 className="font-semibold mb-4">Recent Activity</h3>
            <div className="space-y-4">
                {payments.slice(-5).reverse().map(p => (
                    <div key={p.id} className="flex items-center justify-between text-sm">
                        <div className="flex items-center gap-3">
                            <div className="p-2 bg-green-50 text-green-600 rounded-full"><Wallet className="h-4 w-4"/></div>
                            <div>
                                <p className="font-medium">Payment Received</p>
                                <p className="text-gray-500 text-xs">{p.studentId} paid GH₵ {p.amount}</p>
                            </div>
                        </div>
                        <span className="text-gray-400 text-xs">{new Date(p.datePaid).toLocaleDateString()}</span>
                    </div>
                ))}
            </div>
        </div>
      )}

      {activeTab === 'payments' && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
                <h3 className="font-semibold mb-4 text-gray-800">Record New Payment</h3>
                {payMsg && <div className="mb-4 p-2 bg-green-100 text-green-700 rounded text-sm">{payMsg}</div>}
                <form onSubmit={handlePayment} className="space-y-4">
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Student ID / Index Number</label>
                        <input type="text" required value={payStudentId} onChange={e => setPayStudentId(e.target.value)} className="w-full border border-gray-300 rounded-lg p-2.5 focus:ring-2 focus:ring-green-500 outline-none" placeholder="e.g. NTCW/23/..." />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Receipt Number</label>
                        <input type="text" required value={payReceipt} onChange={e => setPayReceipt(e.target.value)} className="w-full border border-gray-300 rounded-lg p-2.5 focus:ring-2 focus:ring-green-500 outline-none" placeholder="Receipt #" />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Amount (GH₵)</label>
                        <input type="number" required value={payAmount} onChange={e => setPayAmount(Number(e.target.value))} className="w-full border border-gray-300 rounded-lg p-2.5 focus:ring-2 focus:ring-green-500 outline-none" />
                    </div>
                    <button type="submit" className="w-full bg-green-700 hover:bg-green-800 text-white font-medium py-2.5 rounded-lg">Record Transaction</button>
                </form>
            </div>
            
            <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6 overflow-hidden">
                <h3 className="font-semibold mb-4 text-gray-800">Recent Transactions</h3>
                <div className="overflow-y-auto max-h-[400px]">
                    <table className="w-full text-sm text-left">
                        <thead className="text-xs text-gray-500 uppercase bg-gray-50">
                            <tr>
                                <th className="px-3 py-2">Student</th>
                                <th className="px-3 py-2">Receipt</th>
                                <th className="px-3 py-2 text-right">Amt</th>
                            </tr>
                        </thead>
                        <tbody>
                            {payments.slice().reverse().map(p => (
                                <tr key={p.id} className="border-b border-gray-50">
                                    <td className="px-3 py-2">{p.studentId}</td>
                                    <td className="px-3 py-2">{p.receiptNumber}</td>
                                    <td className="px-3 py-2 text-right font-medium">GH₵{p.amount}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
      )}

      {activeTab === 'complaints' && (
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
           <table className="w-full text-sm text-left">
             <thead className="bg-gray-50 text-gray-500 uppercase text-xs">
               <tr>
                 <th className="px-6 py-3">Student</th>
                 <th className="px-6 py-3">Issue</th>
                 <th className="px-6 py-3">Status</th>
                 <th className="px-6 py-3 text-right">Action</th>
               </tr>
             </thead>
             <tbody>
               {complaints.length === 0 ? <tr><td colSpan={4} className="p-6 text-center text-gray-500">No complaints found.</td></tr> : complaints.map(c => (
                 <tr key={c.id} className="border-b border-gray-50">
                   <td className="px-6 py-4 font-medium">{c.studentName}</td>
                   <td className="px-6 py-4">
                     <p className="font-medium text-gray-900">{c.title}</p>
                     <p className="text-gray-500 text-xs truncate max-w-xs">{c.description}</p>
                   </td>
                   <td className="px-6 py-4">
                     <span className={`px-2 py-1 rounded text-xs font-bold ${
                        c.status === ComplaintStatus.RESOLVED ? 'bg-green-100 text-green-700' :
                        c.status === ComplaintStatus.IN_PROGRESS ? 'bg-blue-100 text-blue-700' :
                        'bg-yellow-100 text-yellow-700'
                     }`}>
                        {c.status.replace('_', ' ')}
                     </span>
                   </td>
                   <td className="px-6 py-4 text-right">
                     {c.status !== ComplaintStatus.RESOLVED && (
                        <div className="flex gap-2 justify-end">
                            <button onClick={() => handleStatusChange(c.id, ComplaintStatus.IN_PROGRESS)} className="p-1 hover:bg-gray-100 rounded text-blue-600" title="Mark In Progress"><Clock className="h-4 w-4"/></button>
                            <button onClick={() => handleStatusChange(c.id, ComplaintStatus.RESOLVED)} className="p-1 hover:bg-gray-100 rounded text-green-600" title="Mark Resolved"><CheckCircle className="h-4 w-4"/></button>
                        </div>
                     )}
                   </td>
                 </tr>
               ))}
             </tbody>
           </table>
        </div>
      )}
    </div>
  );
};

export default HallDashboard;