import React, { useState, useEffect } from 'react';
import { useAuth } from '../../contexts/AuthContext';
import { getHalls, getPayments, getComplaints, addComplaint, getSettings } from '../../services/storageService';
import { ComplaintStatus, Complaint, Hall, Payment } from '../../types';
import { CheckCircle, AlertCircle, History, Send, Loader2 } from 'lucide-react';

const StudentDashboard = () => {
  const { user } = useAuth();
  const [newComplaintTitle, setNewComplaintTitle] = useState('');
  const [newComplaintDesc, setNewComplaintDesc] = useState('');
  const [msg, setMsg] = useState('');
  const [loading, setLoading] = useState(true);

  const [hall, setHall] = useState<Hall | undefined>(undefined);
  const [myPayments, setMyPayments] = useState<Payment[]>([]);
  const [myComplaints, setMyComplaints] = useState<Complaint[]>([]);
  const [hasPaidCurrent, setHasPaidCurrent] = useState(false);
  const [currentSemesterKey, setCurrentSemesterKey] = useState('');

  const loadData = async () => {
    if (!user || !user.hallId) return;
    try {
        const [halls, payments, complaints, settings] = await Promise.all([
            getHalls(),
            getPayments(),
            getComplaints(),
            getSettings()
        ]);

        setHall(halls.find(h => h.id === user.hallId));
        setMyPayments(payments.filter(p => p.studentId === user.studentId || p.studentId === user.id));
        setMyComplaints(complaints.filter(c => c.studentId === user.id));
        
        const semKey = `${settings.currentAcademicYear} - Sem ${settings.currentSemester}`;
        setCurrentSemesterKey(semKey);
        
        const paid = payments.some(p => (p.studentId === user.studentId || p.studentId === user.id) && p.semester === semKey);
        setHasPaidCurrent(paid);

    } catch (err) {
        console.error(err);
    } finally {
        setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, [user]);

  const handleSubmitComplaint = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user) return;
    
    const c: Complaint = {
        id: '', // Generated by DB
        studentId: user.id,
        studentName: `${user.firstName} ${user.lastName}`,
        hallId: user.hallId!,
        title: newComplaintTitle,
        description: newComplaintDesc,
        status: ComplaintStatus.PENDING,
        dateSubmitted: new Date().toISOString()
    };
    await addComplaint(c);
    setNewComplaintTitle('');
    setNewComplaintDesc('');
    setMsg('Complaint submitted successfully');
    
    await loadData(); // Refresh list
    setTimeout(() => setMsg(''), 3000);
  };

  if (!user || !user.hallId) return <div>Student Configuration Error</div>;
  if (loading) return <div className="flex h-64 items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-green-600"/></div>;

  return (
    <div className="space-y-6">
      {/* Welcome Banner */}
      <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 flex flex-col md:flex-row justify-between items-center gap-4">
        <div>
           <h1 className="text-2xl font-bold text-gray-800">Welcome, {user.firstName}</h1>
           <p className="text-gray-500">{user.program} - {user.studentId}</p>
        </div>
        <div className={`px-4 py-2 rounded-lg flex items-center gap-2 ${hasPaidCurrent ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>
            {hasPaidCurrent ? <CheckCircle className="h-5 w-5"/> : <AlertCircle className="h-5 w-5"/>}
            <span className="font-semibold">{hasPaidCurrent ? 'Dues Paid' : 'Dues Pending'}</span>
            <span className="text-xs opacity-75 block ml-1">({currentSemesterKey})</span>
        </div>
      </div>

      {/* Hall Info */}
      {hall && (
        <div className="relative rounded-xl overflow-hidden shadow-sm bg-gray-900 text-white">
            <img src={hall.imagePlaceholder} alt={hall.name} className="absolute inset-0 w-full h-full object-cover opacity-20" />
            <div className="relative p-8">
                <h2 className="text-3xl font-bold mb-2">{hall.name}</h2>
                <p className="text-gray-200 max-w-2xl">{hall.description}</p>
                <div className="mt-6 bg-white/10 p-4 rounded-lg backdrop-blur-sm">
                    <h4 className="text-sm font-semibold uppercase text-yellow-400 mb-2">History</h4>
                    <p className="text-sm text-gray-100 leading-relaxed">{hall.history}</p>
                </div>
            </div>
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Payment History */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
            <div className="flex items-center gap-2 mb-4">
                <History className="h-5 w-5 text-green-600" />
                <h3 className="font-semibold text-gray-800">Payment History</h3>
            </div>
            {myPayments.length === 0 ? (
                <p className="text-sm text-gray-500 italic">No payment records found.</p>
            ) : (
                <div className="space-y-3">
                    {myPayments.map(p => (
                        <div key={p.id} className="flex justify-between items-center p-3 bg-gray-50 rounded-lg border border-gray-100">
                            <div>
                                <p className="font-medium text-sm text-gray-800">{p.semester}</p>
                                <p className="text-xs text-gray-500">Receipt: {p.receiptNumber}</p>
                            </div>
                            <span className="font-bold text-green-700">GH₵{p.amount}</span>
                        </div>
                    ))}
                </div>
            )}
        </div>

        {/* Complaints */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
             <div className="flex items-center gap-2 mb-4">
                <Send className="h-5 w-5 text-blue-600" />
                <h3 className="font-semibold text-gray-800">Lodge Complaint</h3>
            </div>
            
            {msg && <div className="mb-3 p-2 bg-green-100 text-green-700 text-xs rounded">{msg}</div>}

            <form onSubmit={handleSubmitComplaint} className="space-y-3 mb-6">
                <input 
                    type="text" 
                    placeholder="Subject (e.g. Broken Fan)" 
                    className="w-full border border-gray-300 rounded p-2 text-sm focus:ring-1 focus:ring-green-500 outline-none"
                    value={newComplaintTitle}
                    onChange={e => setNewComplaintTitle(e.target.value)}
                    required
                />
                <textarea 
                    placeholder="Describe the issue..." 
                    className="w-full border border-gray-300 rounded p-2 text-sm focus:ring-1 focus:ring-green-500 outline-none h-20"
                    value={newComplaintDesc}
                    onChange={e => setNewComplaintDesc(e.target.value)}
                    required
                />
                <button type="submit" className="w-full bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium py-2 rounded transition-colors">Submit Report</button>
            </form>

            <h4 className="text-xs font-semibold text-gray-500 uppercase mb-3">Recent Reports</h4>
            <div className="space-y-3 max-h-40 overflow-y-auto">
                {myComplaints.map(c => (
                     <div key={c.id} className="p-3 bg-gray-50 rounded border border-gray-100 text-sm">
                        <div className="flex justify-between mb-1">
                            <span className="font-medium truncate">{c.title}</span>
                            <span className={`text-[10px] px-1.5 py-0.5 rounded font-bold ${
                                c.status === ComplaintStatus.RESOLVED ? 'bg-green-100 text-green-700' :
                                c.status === ComplaintStatus.IN_PROGRESS ? 'bg-blue-100 text-blue-700' : 'bg-yellow-100 text-yellow-700'
                            }`}>{c.status}</span>
                        </div>
                        <p className="text-xs text-gray-500">{new Date(c.dateSubmitted).toLocaleDateString()}</p>
                     </div>
                ))}
            </div>
        </div>
      </div>
    </div>
  );
};

export default StudentDashboard;